### ISSUE TITLE
Invalid Input

### ISSUE THREAD

**Issue by usman2k** [sandman0/node-red-contrib-qrdecode#2]
Hello. I am getting follwing error. Do you know how to solve it.
Regards,
![error](https://user-images.githubusercontent.com/26162433/108832640-1c174f80-75cc-11eb-93f5-5af4728f0b78.jpg)

**Comment by atomicsamurai** [comment]
Looks like you are using the usbcamera node in "File mode". You have to switch to "Buffer" mode for qrdecode node to get the image data.
![image](https://user-images.githubusercontent.com/16958965/108866630-9c7c8700-75b1-11eb-8bb7-d0b76e64bc45.png)

**Comment by usman2k** [comment]
Thanks for for kind reply.
I have chage the "usbcamera" node in Buffer mode. but I am getting follwing error
![error](https://user-images.githubusercontent.com/26162433/109022406-139e4200-76bc-11eb-8228-2826daaf7ba4.jpg)

While below is attached the flow:
`[{"id":"812f56af.2177c8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"9fa49ad7.874378","type":"inject","z":"812f56af.2177c8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":940,"y":260,"wires":[["99e2874d.d5bea8"]]},{"id":"9c53f4ee.435e68","type":"debug","z":"812f56af.2177c8","name":"USB","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1250,"y":200,"wires":[]},{"id":"eb54c5d1.5bff98","type":"debug","z":"812f56af.2177c8","name":"QR","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1450,"y":280,"wires":[]},{"id":"99e2874d.d5bea8","type":"usbcamera","z":"812f56af.2177c8","filemode":"0","filename":"image01.jpg","filedefpath":"1","filepath":"","fileformat":"jpeg","resolution":"3","name":"","x":1120,"y":260,"wires":[["9c53f4ee.435e68","b7c922f8.17b8e"]]},{"id":"b7c922f8.17b8e","type":"qrdecode","z":"812f56af.2177c8","name":"QR","x":1290,"y":300,"wires":[["eb54c5d1.5bff98"]]}]`

**Comment by atomicsamurai** [comment]
Well, as you can see, the error is coming from `usbcamera` node, not the `qrdecode` node. It is complaining about missing `Commandcam.exe`. If you look at the documentation of `node-red-contrib-usbcamera`, the first line says:
>A Node-RED node to take photos on a Raspberry Pi with a USB camera. This node will only work on an Raspberry Pi with a USB Camera.

So it won't work out of box on Windows.
Upon further investigation, `node-red-contrib-usbcamera` uses https://www.npmjs.com/package/node-webcam, which is supported on Windows. Maybe you need to build your own version of `node-red-contrib-usbcamera` which works on Windows.

**Comment by usman2k** [comment]
Now, I am using USB camera with Raspberry Pi. But I am getting follwing error.
![error](https://user-images.githubusercontent.com/26162433/109139630-00db4a00-775c-11eb-8234-6bf926009d56.jpg)

**Comment by atomicsamurai** [comment]
The positioning of the QR pattern in front of the camera matters. This is more of a trial and error to determine the best placement/position/angle of the code in front of the camera. Is your QR code on paper or on your phone screen? Try with a printed code on paper first and move to using the phone.
